using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Pcc.Plugins.Generator;

/// <summary>
/// Emits <c>Pcc.Plugins.Generated.PccPlugins.Assemblies</c> — the array of assemblies containing
/// concrete <c>Pcc.Plugins.IPlugin</c> implementations — discovered at build time from the
/// referenced (glob'd) plugin projects. Replaces the hand-maintained array in the host's Program.cs.
/// </summary>
[Generator]
public sealed class PluginRegistrationGenerator : IIncrementalGenerator
{
    private const string PluginInterface = "Pcc.Plugins.IPlugin";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pluginTypes = context.CompilationProvider.Select(
            static (compilation, _) => GetPluginTypeNames(compilation));

        context.RegisterSourceOutput(
            pluginTypes,
            static (spc, names) => spc.AddSource("PccPlugins.g.cs", Build(names)));
    }

    private static ImmutableArray<string> GetPluginTypeNames(Compilation compilation)
    {
        var iface = compilation.GetTypeByMetadataName(PluginInterface);
        if (iface is null)
        {
            return ImmutableArray<string>.Empty;
        }

        var abstractions = iface.ContainingAssembly;
        var names = new SortedSet<string>(StringComparer.Ordinal);

        // The compilation's own source types (covers tests that declare the plugin in source).
        Collect(compilation.Assembly.GlobalNamespace, iface, names);

        // Referenced assemblies that reference plugin-abstractions can implement IPlugin (skips the BCL).
        foreach (var asm in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            if (ReferencesAbstractions(asm, abstractions))
            {
                Collect(asm.GlobalNamespace, iface, names);
            }
        }

        return ImmutableArray.CreateRange(names);
    }

    private static bool ReferencesAbstractions(IAssemblySymbol asm, IAssemblySymbol abstractions)
    {
        if (SymbolEqualityComparer.Default.Equals(asm, abstractions))
        {
            return true;
        }

        foreach (var module in asm.Modules)
        {
            foreach (var referenced in module.ReferencedAssemblies)
            {
                if (referenced.Name == abstractions.Name)
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static void Collect(INamespaceSymbol ns, INamedTypeSymbol iface, SortedSet<string> names)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            if (IsPlugin(type, iface))
            {
                names.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            Collect(child, iface, names);
        }
    }

    private static bool IsPlugin(INamedTypeSymbol type, INamedTypeSymbol iface)
    {
        if (type.TypeKind != TypeKind.Class
            || type.IsAbstract
            || type.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        foreach (var implemented in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(implemented, iface))
            {
                return true;
            }
        }

        return false;
    }

    private static SourceText Build(ImmutableArray<string> typeNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Pcc.Plugins.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Plugin assemblies discovered at build time from referenced IPlugin implementations.</summary>");
        sb.AppendLine("public static class PccPlugins");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>One entry per concrete <c>IPlugin</c> implementation found in the referenced plugin projects.</summary>");
        sb.AppendLine("    public static readonly global::System.Reflection.Assembly[] Assemblies = new global::System.Reflection.Assembly[]");
        sb.AppendLine("    {");
        foreach (var name in typeNames)
        {
            sb.Append("        typeof(").Append(name).AppendLine(").Assembly,");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }
}
